### ISSUE TITLE
Is "Playerlist Premium" available if selfhosting the bot?

### ISSUE THREAD

**Issue by NinCollin** [AstreaTSS/RealmsPlayerlistBot#213]
In the description of this feature, it says "Realms Playerlist Premium allows for extra features that otherwise could not be provided by the bot without funding." which I assume is talking about the main bot that's hosted by you.

The main reason for not making this feature freely available seems to be the extra load generated by having this feature available to everyone who invites this particular instance of the bot, which brings me to my question:

Is this feature available in the publicly released source code? If so, would it work by default, or does the source code implement the same paid verification system in your public instance of the bot?

EDIT: Poking around in the example configuration file reveals the option `PREMIUM_ENCRYPTION_KEY`, so I *assume* that the Premium features are publicly available in the source code (and are activated in the same way as on the publicly invite-able instance of the bot)

**Comment by AstreaTSS** [comment]
There is nothing stopping you from easily generating your own premium code via `/generate-code` if you self-host the bot, so you can indeed get premium for free! All of the actual integration with Ko-Fi is handled by another bot anyhow.

**Comment by NinCollin** [comment]
Great, thanks for the clarification!
